POST http://localhost:3000/login HTTP/1.1
content-type: application/json

{
 "username": "a", 
 "password": "b",
  "email": "c@fede.com"
}

###

POST http://localhost:3000/registro HTTP/1.1
content-type: application/json

{
 "username": "a", 
 "password": "b",
 "email": "c@fede.com"
}

###

GET http://localhost:3000/perfil HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MTgsImVtYWlsIjoiY0BmZWRlLmNvbSIsImlhdCI6MTcyNTQ3MDQwNCwiZXhwIjoxNzI1NDc0MDA0fQ.Dwm-Ncv234dQmM_PU-VKZJYycgZAZ-3uvArMuaSncGA