PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "user" (`id` INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE NOT NULL DEFAULT 0, `user` TEXT NOT NULL, `pass` TEXT NOT NULL) STRICT;
INSERT INTO user VALUES(1,'fede','1234');
DELETE FROM sqlite_sequence;
INSERT INTO sqlite_sequence VALUES('user',3);
COMMIT;
